[vc_section 0=""][vc_row 0=""][vc_column 0=""][/vc_column][/vc_row][vc_row full_width="stretch_row" full_height="yes" content_placement="middle" css=".vc_custom_1495739228368{background-image: url(http://67.207.91.196/wp-content/uploads/2017/04/Head.jpg?id=219) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column 0=""][vc_custom_heading text="Best private rooftops " font_container="tag:h1|font_size:55|text_align:center|color:%23ffffff|line_height:0.7" google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:400%20regular%3A400%3Anormal" el_class="title_h1"][vc_custom_heading text="for proposal in nyc" font_container="tag:h1|font_size:55|text_align:center|color:%23ffffff|line_height:0.7" google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:400%20regular%3A400%3Anormal" el_class="title_h1"][vc_btn title="Order Now" style="flat" shape="round" color="white" align="center" css=".vc_custom_1494819960680{margin-top: 80px !important;}" el_class="wpcf7-submit" link="|||" el_id="go_to"][/vc_column][/vc_row][/vc_section][vc_row el_class="max_1170 why_to" css=".vc_custom_1492908880135{background-color: #ffffff !important;}"][vc_column 0=""][vc_custom_heading text="Why to propose " font_container="tag:h2|font_size:22|text_align:center|line_height:0.8" google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:400%20regular%3A400%3Anormal"][vc_custom_heading text="On a private rooftop" font_container="tag:h2|font_size:22|text_align:center|color:%237447ae|line_height:0.5" google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:400%20regular%3A400%3Anormal"][vc_single_image image="15" alignment="center" css=".vc_custom_1492655054168{margin-top: 10px !important;padding-top: 5px !important;}"][vc_row_inner 0=""][vc_column_inner width="1/3"][vc_single_image image="43" img_size="" alignment="center"][vc_custom_heading text="View" font_container="tag:h2|font_size:17|text_align:center|color:%234e4c58" google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:700%20bold%20regular%3A700%3Anormal"][vc_column_text 0=""]
<p style="text-align: center;"><span style="color: #4e4c58;">You will have an amazing view to the city skyline. Empire State Building, Freedom Tower and city skyscrapers is exactly what you need for a romantic mood.</span></p>
[/vc_column_text][/vc_column_inner][vc_column_inner width="1/3"][vc_single_image image="45" img_size="" alignment="center"][vc_custom_heading text="Privacy" font_container="tag:h2|font_size:17|text_align:center|color:%234e4c58" google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:700%20bold%20regular%3A700%3Anormal"][vc_column_text 0=""]
<p style="text-align: center;"><span style="color: #4e4c58;">You will have an amazing view to the city skyline. Empire State Building, Freedom Tower and city skyscrapers is exactly what you need for a romantic mood.</span></p>
[/vc_column_text][/vc_column_inner][vc_column_inner width="1/3"][vc_single_image image="46" img_size="" alignment="center"][vc_custom_heading text="Decorations" font_container="tag:h2|font_size:17|text_align:center|color:%234e4c58" google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:700%20bold%20regular%3A700%3Anormal"][vc_column_text 0=""]
<p style="text-align: center;"><span style="color: #4e4c58;">You will have an amazing view to the city skyline. Empire State Building, Freedom Tower and city skyscrapers is exactly what you need for a romantic mood.</span></p>
[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1494820080886{margin-top: 120px !important;}" el_class="max_1170" el_id="order_now"][vc_column 0=""][vc_custom_heading text="Our rooftops" font_container="tag:h2|font_size:22|text_align:center|line_height:0.8" google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:400%20regular%3A400%3Anormal"][vc_single_image image="15" alignment="center" css=".vc_custom_1492655054168{margin-top: 10px !important;padding-top: 5px !important;}"][vc_row_inner el_class="gallery_row" css=".vc_custom_1493113800658{margin-top: -10px !important;}"][vc_column_inner][shortcode_homepage_gallery][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1493113643856{margin-top: 70px !important;}"][vc_column 0=""][vc_custom_heading text="Client say" font_container="tag:h2|font_size:22|text_align:center|line_height:0.8" google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:400%20regular%3A400%3Anormal"][vc_single_image image="15" alignment="center" css=".vc_custom_1492655054168{margin-top: 10px !important;padding-top: 5px !important;}"][vc_row_inner css=".vc_custom_1493113886438{margin-top: -30px !important;}"][vc_column_inner 0=""][shortcode_homepage_carousel 0=""][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1493113595395{margin-top: 80px !important;}"][vc_column 0=""][vc_custom_heading text="Who we are" font_container="tag:h2|font_size:22|text_align:center|line_height:0.8" google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:400%20regular%3A400%3Anormal"][vc_single_image image="15" alignment="center" css=".vc_custom_1492655054168{margin-top: 10px !important;padding-top: 5px !important;}"][vc_row_inner 0=""][vc_column_inner width="1/2"][vc_single_image image="230" img_size="large" alignment="right"][/vc_column_inner][vc_column_inner el_class="max_400 who_we_are" width="1/2"][vc_column_text 0=""]RooftopProposal.nyc is the part of "Proposal007" - the leading NYC based proposal planning and photography company. Launched by two professionals - famous NYC proposal photographer and filmmaker Vlad Leto and Tatiana Caicedo, wedding and proposal planner. Over the past 5 years Proposal 007 helped plan and capture more than 1000 proposals in NYC.[/vc_column_text][vc_column_text 0=""]
<div class="item">

<img class="alignnone size-full wp-image-118" style="float: left;" src="http://67.207.91.196/wp-content/uploads/2017/04/who3.png" alt="" width="40" height="40" />
<div>

     +1 (347) 926-9458
<div class="textwidget"></div>
</div>
</div>
<div class="item">

<img class="alignnone size-full wp-image-117" style="float: left;" src="http://67.207.91.196/wp-content/uploads/2017/04/who2.png" alt="" width="40" height="40" />
<div class="who_item">
<div class="_h8t">
<div id="js_r1" class="_5wd9 direction_ltr" data-tooltip-content="1:22pm" data-hover="tooltip" data-tooltip-position="right">
<div class="_5wde _n4o">
<div class="_5w1r _3_om _5wdf">
<div class="_4gx_">
<div class="_d97"><span class="_5yl5">info@rooftopproposal.nyc</span></div>
</div>
</div>
</div>
</div>
</div>
&nbsp;

</div>
</div>
<div class="item"></div>
[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1492758323464{margin-top: 100px !important;padding-top: 60px !important;padding-bottom: 60px !important;background-image: url(http://67.207.91.196/wp-content/uploads/2017/04/fon.png?id=21) !important;}"][vc_column][vc_custom_heading text="Still have questions" font_container="tag:h2|font_size:22|text_align:center|color:%23ffffff|line_height:0.8" google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:400%20regular%3A400%3Anormal"][vc_single_image image="33" alignment="center" css=".vc_custom_1492758602112{margin-top: 10px !important;padding-top: 5px !important;}"][contact-form-7 id="294" title="homepage form"][/vc_column][/vc_row]